/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ApiBridgeCommandsRouteImport } from './routes/api/bridge/commands'
import { Route as ApiBridgeEventsRouteImport } from './routes/api/bridge/events'
import { Route as ApiBridgeHeartbeatRouteImport } from './routes/api/bridge/heartbeat'
import { Route as ApiBridgePairRouteImport } from './routes/api/bridge/pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeCommandsRoute = ApiBridgeCommandsRouteImport.update({
  id: '/api/bridge/commands',
  path: '/api/bridge/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeEventsRoute = ApiBridgeEventsRouteImport.update({
  id: '/api/bridge/events',
  path: '/api/bridge/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeHeartbeatRoute = ApiBridgeHeartbeatRouteImport.update({
  id: '/api/bridge/heartbeat',
  path: '/api/bridge/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgePairRoute = ApiBridgePairRouteImport.update({
  id: '/api/bridge/pair',
  path: '/api/bridge/pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/api/bridge/commands': typeof ApiBridgeCommandsRoute
  '/api/bridge/events': typeof ApiBridgeEventsRoute
  '/api/bridge/heartbeat': typeof ApiBridgeHeartbeatRoute
  '/api/bridge/pair': typeof ApiBridgePairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/api/bridge/commands': typeof ApiBridgeCommandsRoute
  '/api/bridge/events': typeof ApiBridgeEventsRoute
  '/api/bridge/heartbeat': typeof ApiBridgeHeartbeatRoute
  '/api/bridge/pair': typeof ApiBridgePairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/api/bridge/commands': typeof ApiBridgeCommandsRoute
  '/api/bridge/events': typeof ApiBridgeEventsRoute
  '/api/bridge/heartbeat': typeof ApiBridgeHeartbeatRoute
  '/api/bridge/pair': typeof ApiBridgePairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/api/bridge/commands'
    | '/api/bridge/events'
    | '/api/bridge/heartbeat'
    | '/api/bridge/pair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/api/bridge/commands'
    | '/api/bridge/events'
    | '/api/bridge/heartbeat'
    | '/api/bridge/pair'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/api/bridge/commands'
    | '/api/bridge/events'
    | '/api/bridge/heartbeat'
    | '/api/bridge/pair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  ApiBridgeCommandsRoute: typeof ApiBridgeCommandsRoute
  ApiBridgeEventsRoute: typeof ApiBridgeEventsRoute
  ApiBridgeHeartbeatRoute: typeof ApiBridgeHeartbeatRoute
  ApiBridgePairRoute: typeof ApiBridgePairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/commands': {
      id: '/api/bridge/commands'
      path: '/api/bridge/commands'
      fullPath: '/api/bridge/commands'
      preLoaderRoute: typeof ApiBridgeCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/events': {
      id: '/api/bridge/events'
      path: '/api/bridge/events'
      fullPath: '/api/bridge/events'
      preLoaderRoute: typeof ApiBridgeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/heartbeat': {
      id: '/api/bridge/heartbeat'
      path: '/api/bridge/heartbeat'
      fullPath: '/api/bridge/heartbeat'
      preLoaderRoute: typeof ApiBridgeHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/pair': {
      id: '/api/bridge/pair'
      path: '/api/bridge/pair'
      fullPath: '/api/bridge/pair'
      preLoaderRoute: typeof ApiBridgePairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  ApiBridgeCommandsRoute: ApiBridgeCommandsRoute,
  ApiBridgeEventsRoute: ApiBridgeEventsRoute,
  ApiBridgeHeartbeatRoute: ApiBridgeHeartbeatRoute,
  ApiBridgePairRoute: ApiBridgePairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
